### ISSUE TITLE
Enable GPU acceleration in containers

### ISSUE THREAD

**Issue by a-to-the-5** [cloudflightio/dockerinwsl#16]
It is possible to have GPU acceleration in docker containers in WSL as explained in [this guide](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#gpu-accelerated-computing). 
However, [Installing the Nvidia Docker Toolkit](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#ch04-sub02-install-nvidia-docker) is not so simple on **dockerinwsl**, since alpine has no pre-built package provided by Nvidia ([list of supported distros](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#linux-distributions)).
This could be solved by either:

- switching to an Ubuntu-based distro for **dockerinwsl** (or providing another flavor that is based on Ubuntu and has GPU acceleration)
- building the Nvidia toolkit for apline and bundling it along with the base image.

**Comment by mriedmann** [comment]
FYI: It might be needed to switch to ubuntu anyways (see #13). Maybe this gets easier then.

**Comment by mriedmann** [comment]
DockerInWSL 1.2.x is now based on Ubuntu. Feel free to experiment with. You can enter the distro by executing `wsl -d clf_dockerinwsl` in a normal shell. After that you should be able to use it like any other wsl2 ubuntu installation (besides some networking weirdness because of docker and vpnkit).

Would be great if you could add your experiments to our wiki (https://github.com/cloudflightio/dockerinwsl/wiki) :)

**Comment by alexanderfreller** [comment]
I just tried to enable GPU acceleration. 
These steps worked for me: https://docs.nvidia.com/cuda/wsl-user-guide/index.html#ch04-sub02-install-nvidia-docker

**Comment by mriedmann** [comment]
This project has been discontinued.
